---
- name: Push {{ site }} database from development to {{ env }}
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"

  vars_files:
    - group_vars/development/wordpress_sites.yml

  vars:
    project_root: "{{ www_root }}/{{ site }}"
    project_web_dir: "{{ project_root }}/current"
    dev_wordpress_sites: "{{ lookup('file', 'group_vars/development/wordpress_sites.yml') | from_yaml }}"
    url_from: "{{ dev_wordpress_sites.wordpress_sites[site].site_hosts.0.canonical }}"
    url_to: "{{ wordpress_sites[site].site_hosts.0.canonical }}"
    local_bedrock_dir: "{{ dev_wordpress_sites.wordpress_sites[site].local_path }}"
    dump_file: "{{ site | regex_replace('\\.+', '_') }}_db_dump.sql.gz"
    current_date_and_time: "{{ ansible_date_time.date | regex_replace('\\-+', '_') }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}"
    backup_file: "{{ site | regex_replace('\\.+', '_') }}_{{ env }}_{{ current_date_and_time }}.sql.gz"

  tasks:
  - name: Abort if environment variable is equal to development
    fail:
      msg: "ERROR: development is not a valid environment for this mode (you can't push from development to development)."
    when: env == "development"

  - name: Check if {{ site }} local folder exists
    delegate_to: localhost
    stat:
      path: "{{ local_bedrock_dir }}"
    register: result
    become: no

  - name: Abort if {{ site }} local folder doesn't exist
    fail:
      msg: "ERROR: {{ site }} is not a valid site (local folder {{ local_bedrock_dir }} does not exist)."
    when: result.stat.exists is defined and result.stat.exists == false or result.stat.isdir is defined and result.stat.isdir == false

  - block:
    - name: Create local database_backup directory if it doesn't exist
      delegate_to: localhost
      file:
        path: "{{ local_bedrock_dir }}/database_backup"
        state: directory
        mode: 0755
      become: no

    - name: Create database dump on development
      delegate_to: localhost
      shell: wp db export --allow-root - | gzip > {{ dump_file }}
      args:
        chdir: "{{ local_bedrock_dir }}/web/wp"
      become: no

    - name: Push database dump from development to {{ env }}
      copy:
        src: "{{ local_bedrock_dir }}/{{ dump_file }}"
        dest: "{{ project_web_dir }}/{{ dump_file }}"

    - name: Delete database dump from development
      delegate_to: localhost
      shell: rm -f {{ dump_file }}
      args:
        chdir: "{{ local_bedrock_dir }}"
      become: no

    - name: Export {{ env }} database before importing dump (backup)
      shell: wp db export - | gzip > {{ backup_file }}
      args:
        chdir: "{{ project_web_dir }}"

    - name: Pull exported database from {{ env }} to development (backup)
      fetch:
        src: "{{project_web_dir}}/{{ backup_file }}"
        dest: "{{ local_bedrock_dir }}/database_backup/"
        flat: yes

    - name: Delete exported database from {{ env }} (backup)
      shell: rm -f {{ backup_file }}
      args:
        chdir: "{{ project_web_dir }}"

    - name: Import database dump on {{ env }}
      shell: gzip -c -d {{ dump_file }} | wp db import -
      args:
        chdir: "{{ project_web_dir }}"

    - name: Delete database dump from {{ env }}
      shell: rm -f {{ dump_file }}
      args:
        chdir: "{{ project_web_dir }}"

    - name: Search for {{ url_from }} and replace with {{ url_to }} on development
      command: wp search-replace '//{{ url_from }}' '//{{ url_to }}' --allow-root --all-tables --precise
      args:
        chdir: "{{ project_web_dir }}"
      tags: ['search-replace']
    when: result.stat.exists is defined and result.stat.exists and result.stat.isdir is defined and result.stat.isdir
